# Generated by Django 5.2 on 2025-04-16 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inteligencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policial',
            options={'ordering': ['post_grad__id'], 'verbose_name': 'Policial', 'verbose_name_plural': 'Policiais'},
        ),
        migrations.AlterField(
            model_name='policial',
            name='post_grad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policiais', to='inteligencia.postgrad', verbose_name='Post/Grad'),
        ),
        migrations.AlterField(
            model_name='policial',
            name='re',
            field=models.CharField(max_length=9, unique=True, verbose_name='R.E.'),
        ),
    ]
